name: synth-cargo-test

on:
  push:
    branches: [master]
    paths: ["**/*.rs"]
  pull_request:
    branches: [master]
    paths: ["**/*.rs"]

  workflow_dispatch:

jobs:
  cargo_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo test
  clippy_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
      - run: cargo clippy --tests --all-targets -- -D warnings
  telemetry_test:     
    runs-on: ubuntu-latest     
    steps:     
      - uses: actions/checkout@v2     
      - uses: actions-rs/toolchain@v1     
        with:     
          toolchain: nightly-2022-08-01     
      - run: cargo install --locked --debug --path=synth --features = telemetry           
  fmt_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check
